version: "3.7"

services:
  web:
    image: nginx:alpine
    ports:
      - 8083:80
    volumes:
      - type: bind
        source: ./
        target: /var/www
        consistency: cached
      - ./docker/etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - www
  phpfpm:
    build:
      context: ./docker
      dockerfile: php.dockerfile
    volumes:
      - type: bind
        source: ./
        target: /var/www
        consistency: cached
      - ./tmp/grinds:/tmp/grinds
    networks:
      - www
    environment:
      XDEBUG_CONFIG: client_host=${MYIP}
      DEBUG: 1
    working_dir: /var/www

networks:
  www:
